export const ECONOMY_CONSTANTS = {
  DEFAULT_TREASURY: 1000000,
  DEFAULT_GDP_GROWTH: 0,
  DEFAULT_INFLATION: 2,
  DEFAULT_UNEMPLOYMENT: 5,
  DEFAULT_DEBT: 0,
  DEFAULT_CREDIT_RATING: 'BBB',
  DEFAULT_MARKET_STABILITY: 100,
  DEFAULT_TRADE_BALANCE: 0,
} as const;
