export const RESOURCE_CONSTANTS = {
  DEFAULT_BASE_PRICE: 100,
  DEFAULT_VOLATILITY: 0.1,
  MIN_PRICE_FACTOR: 0.5,
  MAX_PRICE_FACTOR: 2,
  DEFAULT_EFFICIENCY: 1,
  DEFAULT_CAPACITY: 1000,
  DEFAULT_IS_ACTIVE: true,
} as const;
